module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--color-background))",
        foreground: "hsl(var(--color-foreground))",
        card: "hsl(var(--color-card))",
        "card-foreground": "hsl(var(--color-card-foreground))",
        popover: "hsl(var(--color-popover))",
        "popover-foreground": "hsl(var(--color-popover-foreground))",
        primary: "hsl(var(--color-primary))",
        "primary-foreground": "hsl(var(--color-primary-foreground))",
        secondary: "hsl(var(--color-secondary))",
        "secondary-foreground": "hsl(var(--color-secondary-foreground))",
        "category-movies": "hsl(var(--color-category-movies))",
        "category-series": "hsl(var(--color-category-series))",
        "category-anime": "hsl(var(--color-category-anime))",
        "category-drama": "hsl(var(--color-category-drama))",
        "category-variety": "hsl(var(--color-category-variety))",
        "category-foreground": "hsl(var(--color-category-foreground))",
        accent: "hsl(var(--color-accent))",
        "accent-foreground": "hsl(var(--color-accent-foreground))",
        border: "hsl(var(--color-border))",
        input: "hsl(var(--color-input))",
        ring: "hsl(var(--color-ring))",
        muted: "hsl(var(--color-muted))",
        "muted-foreground": "hsl(var(--color-muted-foreground))",
        success: "hsl(var(--color-success))",
        "success-foreground": "hsl(var(--color-success-foreground))",
        warning: "hsl(var(--color-warning))",
        "warning-foreground": "hsl(var(--color-warning-foreground))",
        error: "hsl(var(--color-error))",
        "error-foreground": "hsl(var(--color-error-foreground))",
        info: "hsl(var(--color-info))",
        "info-foreground": "hsl(var(--color-info-foreground))",
        surface: "hsl(var(--color-surface))",
        "surface-foreground": "hsl(var(--color-surface-foreground))",
        gray: {
          50: "hsl(var(--color-gray-50))",
          100: "hsl(var(--color-gray-100))",
          200: "hsl(var(--color-gray-200))",
          300: "hsl(var(--color-gray-300))",
          400: "hsl(var(--color-gray-400))",
          500: "hsl(var(--color-gray-500))",
          600: "hsl(var(--color-gray-600))",
          700: "hsl(var(--color-gray-700))",
          800: "hsl(var(--color-gray-800))",
          900: "hsl(var(--color-gray-900))",
        },
      },
      fontFamily: {
        sans: ['"DM Sans"', "sans-serif"],
        body: ['"Inter"', "sans-serif"],
        mono: ['"IBM Plex Mono"', "monospace"],
      },
      backgroundImage: {
        "gradient-primary": "var(--gradient-primary)",
        "gradient-secondary": "var(--gradient-secondary)",
        "gradient-accent": "var(--gradient-accent)",
        "button-gradient-fill": "var(--gradient-primary)",
        "button-border-gradient": "var(--gradient-accent)",
        "hero-overlay": "var(--gradient-hero-overlay)",
        "surface-overlay":
          "linear-gradient(180deg, hsl(var(--color-background) / 0.1), hsl(var(--color-background) / 0.7))",
      },
      maxWidth: {
        container: "1440px",
      },
      borderRadius: {
        sm: "6px",
        md: "8px",
        lg: "12px",
        xl: "16px",
      },
      boxShadow: {
        none: "none",
      },
      transitionTimingFunction: {
        cinematic: "cubic-bezier(0.4, 0, 0.2, 1)",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        pulseRing: {
          "0%, 100%": { boxShadow: "0 0 0 0 hsl(var(--color-ring) / 0.2)" },
          "50%": { boxShadow: "0 0 0 6px hsl(var(--color-ring) / 0.05)" },
        },
      },
      animation: {
        shimmer: "shimmer 1.8s linear infinite",
        "pulse-ring": "pulseRing 1.8s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
