name = "streamxie"
compatibility_date = "2026-05-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "AUTH_DB"
database_name = "streamxie-auth"
database_id = "48a91a1b-f6d5-4d3f-88da-20b58655e5fb"
